# Generated by Django 4.2.6 on 2023-11-07 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано в: ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновленно в: ')),
                ('category', models.CharField(choices=[('alcohol', 'Алгокольный'), ('notAlcohol', 'Безалкогольный')], default='alcohol', max_length=40, verbose_name='Категория')),
                ('name', models.CharField(max_length=120, verbose_name='Наименование')),
                ('identification_number', models.CharField(max_length=100, verbose_name='ID')),
                ('unit', models.CharField(choices=[('item', 'шт'), ('kilogram', 'кг'), ('liter', 'литр'), ('m', 'м')], default='item', max_length=8, verbose_name='Ед.измерения')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('abstractproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.abstractproduct')),
                ('quantity', models.IntegerField(default=1, verbose_name='Кол-во')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('sum', models.IntegerField(default=0, verbose_name='Сумма')),
                ('state', models.CharField(choices=[('Normal', 'Норма'), ('Invalid', 'Брак')], default='НОРМА', max_length=20, verbose_name='Состояние')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Архив? ')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
            bases=('product.abstractproduct',),
        ),
    ]
