# Generated by Django 4.2.4 on 2023-10-11 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('identification_number', models.AutoField(primary_key=True, serialize=False)),
                ('unit_of_measurement', models.CharField(default='литр', max_length=10)),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.IntegerField()),
                ('status', models.CharField(choices=[('НОРМА', 'НОРМА'), ('брак', 'Брак'), ('просроченный', 'Просроченный')], default='НОРМА', max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
        ),
        migrations.CreateModel(
            name='ArchiveProduct',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('identification_number', models.AutoField(primary_key=True, serialize=False)),
                ('unit_of_measurement', models.CharField(default='литр', max_length=10)),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.IntegerField()),
                ('status', models.CharField(choices=[('НОРМА', 'НОРМА'), ('брак', 'Брак'), ('просроченный', 'Просроченный')], default='НОРМА', max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
        ),
    ]
