# Generated by Django 4.2.4 on 2023-10-08 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('НОРМА', 'НОРМА'), ('брак', 'Брак'), ('просроченный', 'Просроченный')], default='НОРМА', max_length=20),
        ),
    ]
