# Generated by Django 4.2.6 on 2023-12-02 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название склада')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склад',
            },
        ),
        migrations.AlterModelOptions(
            name='productdefect',
            options={'verbose_name': 'Бракованные товары', 'verbose_name_plural': 'Бракованные товары'},
        ),
        migrations.RemoveField(
            model_name='productdefect',
            name='category',
        ),
        migrations.RemoveField(
            model_name='productdefect',
            name='identification_number',
        ),
        migrations.RemoveField(
            model_name='productdefect',
            name='is_archived',
        ),
        migrations.RemoveField(
            model_name='productdefect',
            name='name',
        ),
        migrations.RemoveField(
            model_name='productdefect',
            name='price',
        ),
        migrations.RemoveField(
            model_name='productdefect',
            name='state',
        ),
        migrations.RemoveField(
            model_name='productdefect',
            name='sum',
        ),
        migrations.RemoveField(
            model_name='productdefect',
            name='unit',
        ),
        migrations.AddField(
            model_name='productdefect',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='defective_products', to='product.productnormal', verbose_name='Бракованный товар'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productdefect',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Колличество'),
        ),
    ]
