# Generated by Django 4.2.6 on 2023-10-21 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='В АРХИВ'),
        ),
    ]
