# Generated by Django 4.2.6 on 2023-11-14 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='identification_number',
            field=models.IntegerField(verbose_name='ID'),
        ),
    ]
