# Generated by Django 4.2.6 on 2023-11-10 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='state',
            field=models.CharField(choices=[('Normal', 'Норма'), ('Invalid', 'Брак')], default='Normal', max_length=20, verbose_name='Состояние'),
        ),
    ]
