# Generated by Django 4.2.7 on 2023-11-03 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='state',
            field=models.CharField(choices=[('Normal', 'Норма'), ('Invalid', 'Брак')], default='НОРМА', max_length=20, verbose_name='Состояние'),
        ),
    ]
