# Generated by Django 4.2.4 on 2023-10-12 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_reate_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='reate_data',
            new_name='create_data',
        ),
    ]
