# Generated by Django 4.2.6 on 2023-11-26 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='identification_number',
            field=models.CharField(max_length=200, unique=True, verbose_name='ID'),
        ),
    ]
