# Generated by Django 4.2.6 on 2023-11-14 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_identification_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='identification_number',
            field=models.IntegerField(unique=True, verbose_name='ID'),
        ),
    ]
