# Generated by Django 4.2.6 on 2023-11-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_identification_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=120, unique=True, verbose_name='Наименование'),
        ),
    ]
