# Generated by Django 4.2.6 on 2023-12-02 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productnormal_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdefect',
            name='warehouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='defect_products', to='product.warehouse', verbose_name='Склад (бракованный товар)'),
            preserve_default=False,
        ),
    ]
