# Generated by Django 4.2.6 on 2023-10-27 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productitem_remove_product_category_delete_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='state',
            field=models.CharField(choices=[('Normal', 'Норма'), ('Invalid', 'Брак')], max_length=20, verbose_name='Состояние'),
        ),
    ]
