# Generated by Django 4.2.6 on 2023-11-10 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_category_product_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='category',
        ),
    ]
