# Generated by Django 4.2.6 on 2023-11-03 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_productitem_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
    ]
