# Generated by Django 4.2.7 on 2023-11-07 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_productitem_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='identification_number',
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='name',
        ),
        migrations.CreateModel(
            name='AbstractProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано в: ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновленно в: ')),
                ('name', models.CharField(max_length=120, verbose_name='Наименование')),
                ('identification_number', models.CharField(max_length=100, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.category')),
            ],
            options={
                'verbose_name': 'AbstractProduct',
                'verbose_name_plural': 'AbstractProducts',
            },
        ),
        migrations.AddField(
            model_name='productitem',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.abstractproduct'),
            preserve_default=False,
        ),
    ]
