# Generated by Django 4.2.6 on 2023-11-04 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_category_alter_productitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='category',
            field=models.CharField(choices=[('alcohol', 'Алгокольный'), ('notAlcohol', 'Безалкогольный')], default='alcohol', max_length=40, verbose_name='Категория'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
