# Generated by Django 4.2.7 on 2023-11-04 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_productitem_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productitem',
            name='created_by',
        ),
    ]
