# Generated by Django 4.2.6 on 2023-12-03 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_productdefect_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdefect',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='defect_products', to='product.warehouse', verbose_name='Склад (бракованный товар)'),
        ),
    ]
