# Generated by Django 4.2.7 on 2023-11-07 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_productitem_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractproduct',
            name='unit',
            field=models.CharField(choices=[('item', 'шт'), ('kilogram', 'кг'), ('liter', 'литр'), ('m', 'м')], default='item', max_length=8, verbose_name='Ед.измерения'),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.abstractproduct'),
        ),
    ]
