# Generated by Django 4.2.6 on 2023-11-10 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_productitem_delete_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='identification_number',
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='name',
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='unit',
        ),
        migrations.CreateModel(
            name='AbstractProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано в: ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновленно в: ')),
                ('name', models.CharField(max_length=120, verbose_name='Наименование')),
                ('identification_number', models.CharField(max_length=100, unique=True, verbose_name='ID')),
                ('unit', models.CharField(choices=[('item', 'шт'), ('kilogram', 'кг'), ('liter', 'литр'), ('m', 'м')], default='item', max_length=10, verbose_name='Ед.измерения')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='productitem',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.abstractproduct'),
            preserve_default=False,
        ),
    ]
