# Generated by Django 4.2.6 on 2023-11-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_productitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='identification_number',
            field=models.CharField(max_length=100, verbose_name='ID'),
        ),
    ]
