# Generated by Django 4.2.6 on 2023-11-03 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_productitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='category',
            field=models.CharField(choices=[('alcohol', 'Алгокольный'), ('notAlcohol', 'Безалкогольный')], default='alcohol', max_length=40, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена'),
        ),
    ]
