# Generated by Django 4.2.6 on 2023-11-30 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_delete_product_productnormal_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категория товаров'},
        ),
        migrations.AlterModelOptions(
            name='productdefect',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Склад-Брак-Товаров'},
        ),
        migrations.AlterModelOptions(
            name='productnormal',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Склад-Норм-Товаров'},
        ),
    ]
