# Generated by Django 4.2.7 on 2023-11-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_productitem_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='создано в: '),
        ),
    ]
