# Generated by Django 4.2.7 on 2023-11-07 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_abstractproduct_unit_alter_productitem_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productitem',
            name='container',
        ),
        migrations.DeleteModel(
            name='Container',
        ),
    ]
