# Generated by Django 4.2.6 on 2023-11-11 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_abstarctproduct_product_remove_productitem_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstarctproduct',
            name='unit',
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('item', 'шт'), ('kilogram', 'кг'), ('liter', 'литр')], default='item', max_length=8, verbose_name='Ед.измерения'),
        ),
    ]
