# Generated by Django 4.2.6 on 2023-12-05 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_productdefect_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdefect',
            name='warehouse',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, related_name='defect_products', to='product.warehouse', verbose_name='Склад (бракованный товар)'),
        ),
        migrations.AlterField(
            model_name='productnormal',
            name='warehouse',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='normal_products', to='product.warehouse', verbose_name='Склад (нормальный товар)'),
        ),
    ]
