# Generated by Django 4.2.6 on 2023-12-05 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_productdefect_warehouse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdefect',
            name='delete_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='удалено в: '),
        ),
        migrations.AddField(
            model_name='productnormal',
            name='delete_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='удалено в: '),
        ),
    ]
