# Generated by Django 4.2.6 on 2023-12-05 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_productdefect_delete_at_productnormal_delete_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdefect',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Архив? '),
        ),
    ]
