version: '3.9'
services:
  backend:
    build:
      context:  ./apps
      dockerfile: DockerFile
    container_name: backend
    env_file:
      - apps/.env
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    networks:
      - backend
    volumes:
      -  .:/kolos_warehouse
  postgres-db:
      image: 'postgres:16'
      volumes:
        - postgres-data:/var/lib/postgresql/data
      ports:
        - "5434:5432"
      environment:
        POSTGRES_DB: ${DB_NAME}
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
networks:
  backend:
    driver: bridge
volumes:
  postgres-data:

