# Generated by Django 4.2.6 on 2023-11-06 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_loginattempt_options_and_more'),
        ('users', '0004_role_user'),
    ]

    operations = [
    ]
