# Generated by Django 4.2.6 on 2023-11-07 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_merge_20231106_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
