# Generated by Django 4.2.6 on 2023-11-30 13:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('distributor', '0010_remove_distributor_passport_id_and_more'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification_number_invoice', models.CharField(max_length=128, verbose_name='Номер накладной продажи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания накладной продажи')),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distrib_invoice', to='distributor.distributor', verbose_name='дистрибьютор')),
            ],
            options={
                'verbose_name': 'Продажа',
                'verbose_name_plural': 'Продажи',
            },
        ),
        migrations.CreateModel(
            name='InvoiceItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество')),
                ('returned', models.BooleanField(default=False, verbose_name='Продана')),
                ('sale_date', models.DateField(auto_now_add=True, verbose_name='Дата продажи')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_product', to='transaction.invoice', verbose_name='Накладная')),
                ('product', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='product.productnormal', verbose_name='Товар из накладной')),
            ],
            options={
                'verbose_name': 'Проданная позиция',
                'verbose_name_plural': 'Проданные позиции',
            },
        ),
        migrations.CreateModel(
            name='ReturnInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification_number_invoice', models.CharField(max_length=128, verbose_name='Номер накладной возврата')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания накладной возврата')),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distrib_invoice_return', to='distributor.distributor', verbose_name='дистрибьютор')),
            ],
            options={
                'verbose_name': 'Возврат',
                'verbose_name_plural': 'Возвраты',
            },
        ),
        migrations.CreateModel(
            name='InvoiceItemsReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество')),
                ('returned', models.BooleanField(default=False, verbose_name='Возвращено')),
                ('returned_date', models.DateField(auto_now_add=True, verbose_name='Дата возврата')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_product_return', to='transaction.invoice', verbose_name='Накладная')),
                ('product', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='transaction.invoiceitems', verbose_name='Товар из накладной')),
            ],
            options={
                'verbose_name': 'Возвращенная  позиция',
                'verbose_name_plural': 'Возвращенные позиции',
            },
        ),
    ]
