# Generated by Django 4.2.6 on 2023-11-16 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('distributor', '0008_distributor_contact2_alter_distributor_contact'),
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distrib_invoice', to='distributor.distributor')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_invoice', to='product.product')),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
