# Generated by Django 4.2.6 on 2023-11-13 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='distributor',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='product',
        ),
        migrations.DeleteModel(
            name='DistributorProduct',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
