# Generated by Django 4.2.6 on 2023-11-20 07:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_updated_at'),
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='product',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания накладной'),
        ),
        migrations.CreateModel(
            name='InvoiceItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество')),
                ('item', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='product.product', verbose_name='Товар из накладной')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='products',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_invoice', to='transaction.invoiceitems', verbose_name='товары из накладной'),
            preserve_default=False,
        ),
    ]
