# Generated by Django 4.2.6 on 2023-11-20 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_updated_at'),
        ('transaction', '0002_remove_invoice_product_remove_invoice_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitems',
            name='item',
        ),
        migrations.AddField(
            model_name='invoiceitems',
            name='invoice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_product', to='transaction.invoice', verbose_name='Накладная'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoiceitems',
            name='product',
            field=models.ForeignKey(default=1, max_length=200, on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Товар из накладной'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='products',
        ),
        migrations.AddField(
            model_name='invoice',
            name='products',
            field=models.ManyToManyField(related_name='order', to='product.product', verbose_name='Товары в накладной'),
        ),
    ]
