# Generated by Django 4.2.6 on 2023-11-30 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_returninvoiceitems_alter_returninvoice_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='created_at',
            new_name='sale_date',
        ),
        migrations.RemoveField(
            model_name='invoiceitems',
            name='sale_date',
        ),
    ]
