# Generated by Django 4.2.6 on 2023-11-20 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_remove_invoiceitems_item_invoiceitems_invoice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='products',
        ),
    ]
