# Generated by Django 4.2.6 on 2023-11-16 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
