# Generated by Django 4.2.6 on 2023-11-21 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_remove_invoice_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='identification_number',
            field=models.CharField(blank=True, max_length=128, verbose_name='Номер накладной'),
        ),
    ]
