# Generated by Django 4.2.6 on 2023-11-30 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_rename_created_at_invoice_sale_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='sale_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания накладной продажи'),
        ),
    ]
