# Generated by Django 4.2.6 on 2023-11-16 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_order_is_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_archived',
        ),
    ]
