# Generated by Django 4.2.6 on 2023-11-21 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_invoice_identification_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='identification_number',
            field=models.CharField(max_length=128, verbose_name='Номер накладной'),
        ),
    ]
