# Generated by Django 4.2.6 on 2023-11-30 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_alter_invoice_sale_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returninvoice',
            name='original_invoice',
        ),
    ]
