# Generated by Django 4.2.6 on 2023-11-17 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0009_alter_distributor_passport_series_and_more'),
        ('product', '0008_remove_abstarctproduct_unit_product_unit'),
        ('transaction', '0005_remove_order_is_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='distributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_distributor', to='distributor.distributor'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_product', to='product.product'),
        ),
    ]
