# Generated by Django 4.2.6 on 2023-11-22 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_alter_invoice_identification_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='identification_number',
            new_name='identification_number_invoice',
        ),
    ]
