# Generated by Django 4.2.6 on 2023-11-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0007_rename_identification_number_invoice_identification_number_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='identification_number_invoice',
            field=models.CharField(max_length=128, unique=True, verbose_name='Номер накладной'),
        ),
    ]
