# Generated by Django 4.2.6 on 2023-12-02 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0008_returninvoice_original_invoice_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='returninvoiceitems',
            name='invoice_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='returned_product', to='transaction.invoiceitems', verbose_name='Товар из накладной продажи'),
            preserve_default=False,
        ),
    ]
