# Generated by Django 4.2.6 on 2023-11-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0009_returnitems_defectiveproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnitems',
            name='distributor',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='identification_number_invoice',
            field=models.CharField(max_length=128, verbose_name='Номер накладной'),
        ),
        migrations.DeleteModel(
            name='DefectiveProduct',
        ),
        migrations.DeleteModel(
            name='ReturnItems',
        ),
    ]
