# Generated by Django 4.2.6 on 2023-12-02 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0010_remove_returninvoice_original_invoice_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returninvoiceitems',
            name='product',
        ),
    ]
