# Generated by Django 4.2.6 on 2023-11-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0010_remove_returnitems_distributor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitems',
            name='returned',
            field=models.BooleanField(default=False, verbose_name='Возвращено'),
        ),
    ]
