# Generated by Django 4.2.6 on 2023-11-29 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_productdefect_productnormal_remove_product_category'),
        ('transaction', '0011_invoiceitems_returned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitems',
            name='product',
            field=models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='product.productnormal', verbose_name='Товар из накладной'),
        ),
    ]
