# Generated by Django 4.2.6 on 2023-12-02 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0011_remove_returninvoiceitems_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returninvoiceitems',
            name='invoice_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_inv', to='transaction.invoiceitems', verbose_name='Товар из накладной продажи'),
        ),
    ]
