# Generated by Django 4.2.6 on 2023-11-30 11:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0010_remove_distributor_passport_id_and_more'),
        ('transaction', '0012_alter_invoiceitems_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name': 'Продажа', 'verbose_name_plural': 'Продажи'},
        ),
        migrations.AlterModelOptions(
            name='invoiceitems',
            options={'verbose_name': 'Проданная позиция', 'verbose_name_plural': 'Проданные позиции'},
        ),
        migrations.AddField(
            model_name='invoiceitems',
            name='sale_date',
            field=models.DateField(auto_now_add=True, default=1, verbose_name='Дата продажи'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания накладной продажи'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='identification_number_invoice',
            field=models.CharField(max_length=128, verbose_name='Номер накладной продажи'),
        ),
        migrations.AlterField(
            model_name='invoiceitems',
            name='returned',
            field=models.BooleanField(default=False, verbose_name='Продана'),
        ),
        migrations.CreateModel(
            name='ReturnInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification_number_invoice', models.CharField(max_length=128, verbose_name='Номер накладной возврата')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания накладной возврата')),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distrib_invoice_return', to='distributor.distributor', verbose_name='дистрибьютор')),
            ],
            options={
                'verbose_name': 'Возврат',
                'verbose_name_plural': 'Возвраты',
            },
        ),
        migrations.CreateModel(
            name='InvoiceItemsReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество')),
                ('returned', models.BooleanField(default=False, verbose_name='Возвращено')),
                ('returned_date', models.DateField(auto_now_add=True, verbose_name='Дата возврата')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_product_return', to='transaction.invoice', verbose_name='Накладная')),
                ('product', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='transaction.invoiceitems', verbose_name='Товар из накладной')),
            ],
            options={
                'verbose_name': 'Возвращенная  позиция',
                'verbose_name_plural': 'Возвращенные позиции',
            },
        ),
    ]
