# Generated by Django 4.2.6 on 2023-12-02 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0012_alter_returninvoiceitems_invoice_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returninvoice',
            name='identification_number_return',
        ),
        migrations.AlterField(
            model_name='returninvoiceitems',
            name='invoice_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.invoiceitems', verbose_name='Товар из накладной продажи'),
        ),
    ]
