# Generated by Django 4.2.6 on 2023-12-02 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0013_remove_returninvoice_identification_number_return_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitems',
            name='product',
        ),
        migrations.AddField(
            model_name='invoiceitems',
            name='product_id',
            field=models.PositiveIntegerField(default=1, verbose_name='ID товара из накладной'),
            preserve_default=False,
        ),
    ]
