# Generated by Django 4.2.6 on 2023-12-02 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0014_remove_invoiceitems_product_invoiceitems_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoiceitems',
            old_name='product_id',
            new_name='product',
        ),
    ]
