# Generated by Django 4.2.6 on 2023-12-02 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('transaction', '0015_rename_product_id_invoiceitems_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitems',
            name='product',
            field=models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='product.productnormal', verbose_name='Товар из накладной'),
        ),
    ]
