# Generated by Django 4.2.6 on 2023-11-13 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distributor',
            name='contact1',
        ),
        migrations.RemoveField(
            model_name='distributor',
            name='contact2',
        ),
        migrations.AddField(
            model_name='distributor',
            name='contact',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Контактный номер один'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='passport_series',
            field=models.CharField(max_length=20, unique=True, verbose_name='Серия паспорта'),
        ),
    ]
