# Generated by Django 4.2.4 on 2023-10-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivedistributor',
            name='actual_place_of_residence',
            field=models.CharField(max_length=255, verbose_name='Фактическое место жительства'),
        ),
    ]
