# Generated by Django 4.2.4 on 2023-10-10 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='distributor',
            old_name='registration_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='distributor',
            old_name='date_of_issue',
            new_name='issue_date',
        ),
        migrations.AlterField(
            model_name='distributor',
            name='contact2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Контактный номер два'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='name',
            field=models.CharField(choices=[('Баткен', 'Баткен'), ('Джалал-Абад', 'Джалал-Абад'), ('Иссык-Куль', 'Иссык-Куль'), ('Нарын', 'Нарын'), ('Ош', 'Ош'), ('Талас', 'Талас'), ('Чуй', 'Чуй')], max_length=50, verbose_name='ФИО'),
        ),
    ]
