# Generated by Django 4.2.6 on 2023-10-23 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Contact Phone')),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distributor.distributor')),
            ],
        ),
    ]
