# Generated by Django 4.2.4 on 2023-10-10 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0002_alter_distributor_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributor',
            name='photo',
            field=models.ImageField(upload_to='media/distributor_images/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='region',
            field=models.CharField(choices=[('Баткен', 'Баткен'), ('Джалал-Абад', 'Джалал-Абад'), ('Иссык-Куль', 'Иссык-Куль'), ('Нарын', 'Нарын'), ('Ош', 'Ош'), ('Талас', 'Талас'), ('Чуй', 'Чуй')], max_length=150, verbose_name='Регион'),
        ),
    ]
