# Generated by Django 4.2.6 on 2023-10-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributor',
            name='contact1',
            field=models.IntegerField(default=1, verbose_name='Контактный номер один'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='distributor',
            name='contact2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Контактный номер два'),
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
