# Generated by Django 4.2.4 on 2023-10-11 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0003_archivedobject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArchivedObject',
        ),
    ]
