# Generated by Django 4.2.6 on 2023-11-03 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0003_distributor_contact1_distributor_contact2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/distributor_images/', verbose_name='Фотография'),
        ),
    ]
