# Generated by Django 4.2.4 on 2023-10-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0003_alter_distributor_photo_alter_distributor_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributor',
            name='archived_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
