<<<<<<< HEAD
# Generated by Django 4.2.6 on 2023-11-03 07:50
=======
# Generated by Django 4.2.7 on 2023-11-02 06:13
>>>>>>> c23d33b2af3a4690362e9e90a2e67798279347d8

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0003_distributor_contact1_distributor_contact2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/distributor_images/', verbose_name='Фотография'),
        ),
    ]
