# Generated by Django 4.2.4 on 2023-10-10 09:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0004_distributor_archived_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='distributor',
            options={'verbose_name': 'Дистрибьютор', 'verbose_name_plural': 'Дистрибьюторы'},
        ),
        migrations.AlterField(
            model_name='distributor',
            name='archived_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата архивации'),
            preserve_default=False,
        ),
    ]
