# Generated by Django 4.2.4 on 2023-10-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0005_alter_distributor_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributor',
            name='archived_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата архивации'),
        ),
    ]
