# Generated by Django 4.2.6 on 2023-11-13 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0006_alter_distributor_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributor',
            name='contact',
            field=models.IntegerField(blank=True, null=True, verbose_name='Контактный номер'),
        ),
    ]
