# Generated by Django 4.2.4 on 2023-10-11 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0002_rename_registration_address_distributor_address_and_more'),
        ('distributor', '0006_alter_distributor_archived_date'),
    ]

    operations = [
    ]
