# Generated by Django 4.2.4 on 2023-10-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0007_merge_20231011_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributor',
            name='name',
            field=models.CharField(max_length=50, verbose_name='ФИО'),
        ),
    ]
