# Generated by Django 4.2.6 on 2023-11-17 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0008_distributor_contact2_alter_distributor_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributor',
            name='passport_series',
            field=models.CharField(default='ID', max_length=4, verbose_name='Серия паспорта'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='region',
            field=models.CharField(max_length=150, verbose_name='Регион'),
        ),
    ]
